using Microsoft.EntityFrameworkCore.Migrations;
using System;
using System.Linq;

namespace BLB.Domain.Net.Migrations
{
    public partial class InitialSeed : Migration
    {
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder == null)
                throw new Exception("migrationBuilder is null");

            migrationBuilder.Sql(@"DELETE FROM public.""Stores"" WHERE ""Code""='DEMO-STORE';");

            migrationBuilder.Sql(@"DELETE FROM public.""Users"" WHERE ""UserName""='demo@mydemostore.com';");
        }

        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder == null)
                throw new Exception("migrationBuilder is null");

            var userSalt = new string(Enumerable.Repeat("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789", 12).Select(s => s[new Random().Next(s.Length)]).ToArray());

            migrationBuilder.Sql(@$"INSERT INTO public.""Users""
                (""CreatedAt"", ""CreatedBy"", ""IsDeleteted"", ""IsEnabled"", ""ModifiedAt"", ""ModifiedBy"", ""EmailAddress"", ""ExternalUserId"", ""FirstName"", ""HashedVerificationCode"", ""IsUserLockedOut"", ""IsUserVerified"", ""LastName"", ""Password"", ""StoreId"", ""UserLockedEndDate"", ""UserName"", ""UserSalt"")
                VALUES(CURRENT_TIMESTAMP, 1, false, true, CURRENT_TIMESTAMP, 1, 'demo@mydemostore.com', null, 'Demo', '', false, true, 'User', '', (SELECT ""Id"" FROM public.""Stores"" WHERE ""Code""='DEMO-STORE' LIMIT 1), null, 'demo@mydemostore.com', '{userSalt}');
            ");

            #region "Countries & States"

            migrationBuilder.Sql(@"INSERT INTO public.""Countries""
					(""IsEnabled"", ""Name"", ""ShortCode"", ""LongCode"")
                VALUES (true, 'Afghanistan', 'AF', null),
					(true, 'Albania', 'AL', null),
					(true, 'Algeria', 'DZ', null),
					(true, 'American Samoa', 'AS', null),
					(true, 'Andorra', 'AD', null),
					(true, 'Angola', 'AO', null),
					(true, 'Anguilla', 'AI', null),
					(true, 'Antarctica', 'AQ', null),
					(true, 'Antigua and Barbuda', 'AG', null),
					(true, 'Argentina', 'AR', null),
					(true, 'Armenia', 'AM', null),
					(true, 'Aruba', 'AW', null),
					(true, 'Australia', 'AU', null),
					(true, 'Austria', 'AT', null),
					(true, 'Azerbaijan', 'AZ', null),
					(true, 'Bahamas', 'BS', null),
					(true, 'Bahrain', 'BH', null),
					(true, 'Bangladesh', 'BD', null),
					(true, 'Barbados', 'BB', null),
					(true, 'Belarus', 'BY', null),
					(true, 'Belgium', 'BE', null),
					(true, 'Belize', 'BZ', null),
					(true, 'Benin', 'BJ', null),
					(true, 'Bermuda', 'BM', null),
					(true, 'Bhutan', 'BT', null),
					(true, 'Bolivia, Plurinational State of', 'BO', null),
					(true, 'Bonaire, Sint Eustatius and Saba', 'BQ', null),
					(true, 'Bosnia and Herzegovina', 'BA', null),
					(true, 'Botswana', 'BW', null),
					(true, 'Bouvet Island', 'BV', null),
					(true, 'Brazil', 'BR', null),
					(true, 'British Indian Ocean Territory', 'IO', null),
					(true, 'Brunei Darussalam', 'BN', null),
					(true, 'Bulgaria', 'BG', null),
					(true, 'Burkina Faso', 'BF', null),
					(true, 'Burundi', 'BI', null),
					(true, 'Cambodia', 'KH', null),
					(true, 'Cameroon', 'CM', null),
					(true, 'Canada', 'CA', null),
					(true, 'Cape Verde', 'CV', null),
					(true, 'Cayman Islands', 'KY', null),
					(true, 'Central African Republic', 'CF', null),
					(true, 'Chad', 'TD', null),
					(true, 'Chile', 'CL', null),
					(true, 'China', 'CN', null),
					(true, 'Christmas Island', 'CX', null),
					(true, 'Cocos (Keeling) Islands', 'CC', null),
					(true, 'Colombia', 'CO', null),
					(true, 'Comoros', 'KM', null),
					(true, 'Congo', 'CG', null),
					(true, 'Congo, the Democratic Republic of the', 'CD', null),
					(true, 'Cook Islands', 'CK', null),
					(true, 'Costa Rica', 'CR', null),
					(true, 'CÃ´te d''Ivoire', 'CI', null),
					(true, 'Croatia', 'HR', null),
					(true, 'Cuba', 'CU', null),
					(true, 'CuraÃ§ao', 'CW', null),
					(true, 'Cyprus', 'CY', null),
					(true, 'Czech Republic', 'CZ', null),
					(true, 'Denmark', 'DK', null),
					(true, 'Djibouti', 'DJ', null),
					(true, 'Dominica', 'DM', null),
					(true, 'Dominican Republic', 'DO', null),
					(true, 'Ecuador', 'EC', null),
					(true, 'Egypt', 'EG', null),
					(true, 'El Salvador', 'SV', null),
					(true, 'Equatorial Guinea', 'GQ', null),
					(true, 'Eritrea', 'ER', null),
					(true, 'Estonia', 'EE', null),
					(true, 'Ethiopia', 'ET', null),
					(true, 'Falkland Islands (Malvinas)', 'FK', null),
					(true, 'Faroe Islands', 'FO', null),
					(true, 'Fiji', 'FJ', null),
					(true, 'Finland', 'FI', null),
					(true, 'France', 'FR', null),
					(true, 'French Guiana', 'GF', null),
					(true, 'French Polynesia', 'PF', null),
					(true, 'French Southern Territories', 'TF', null),
					(true, 'Gabon', 'GA', null),
					(true, 'Gambia', 'GM', null),
					(true, 'Georgia', 'GE', null),
					(true, 'Germany', 'DE', null),
					(true, 'Ghana', 'GH', null),
					(true, 'Gibraltar', 'GI', null),
					(true, 'Greece', 'GR', null),
					(true, 'Greenland', 'GL', null),
					(true, 'Grenada', 'GD', null),
					(true, 'Guadeloupe', 'GP', null),
					(true, 'Guam', 'GU', null),
					(true, 'Guatemala', 'GT', null),
					(true, 'Guernsey', 'GG', null),
					(true, 'Guinea', 'GN', null),
					(true, 'Guinea-Bissau', 'GW', null),
					(true, 'Guyana', 'GY', null),
					(true, 'Haiti', 'HT', null),
					(true, 'Heard Island and McDonald Islands', 'HM', null),
					(true, 'Holy See (Vatican City State)', 'VA', null),
					(true, 'Honduras', 'HN', null),
					(true, 'Hong Kong', 'HK', null),
					(true, 'Hungary', 'HU', null),
					(true, 'Iceland', 'IS', null),
					(true, 'India', 'IN', null),
					(true, 'Indonesia', 'ID', null),
					(true, 'Iran, Islamic Republic of', 'IR', null),
					(true, 'Iraq', 'IQ', null),
					(true, 'Ireland', 'IE', null),
					(true, 'Isle of Man', 'IM', null),
					(true, 'Israel', 'IL', null),
					(true, 'Italy', 'IT', null),
					(true, 'Jamaica', 'JM', null),
					(true, 'Japan', 'JP', null),
					(true, 'Jersey', 'JE', null),
					(true, 'Jordan', 'JO', null),
					(true, 'Kazakhstan', 'KZ', null),
					(true, 'Kenya', 'KE', null),
					(true, 'Kiribati', 'KI', null),
					(true, 'Korea, Democratic People''s Republic of', 'KP', null),
					(true, 'Korea, Republic of', 'KR', null),
					(true, 'Kuwait', 'KW', null),
					(true, 'Kyrgyzstan', 'KG', null),
					(true, 'Lao People''s Democratic Republic', 'LA', null),
					(true, 'Latvia', 'LV', null),
					(true, 'Lebanon', 'LB', null),
					(true, 'Lesotho', 'LS', null),
					(true, 'Liberia', 'LR', null),
					(true, 'Libya', 'LY', null),
					(true, 'Liechtenstein', 'LI', null),
					(true, 'Lithuania', 'LT', null),
					(true, 'Luxembourg', 'LU', null),
					(true, 'Macao', 'MO', null),
					(true, 'Macedonia, the Former Yugoslav Republic of', 'MK', null),
					(true, 'Madagascar', 'MG', null),
					(true, 'Malawi', 'MW', null),
					(true, 'Malaysia', 'MY', null),
					(true, 'Maldives', 'MV', null),
					(true, 'Mali', 'ML', null),
					(true, 'Malta', 'MT', null),
					(true, 'Marshall Islands', 'MH', null),
					(true, 'Martinique', 'MQ', null),
					(true, 'Mauritania', 'MR', null),
					(true, 'Mauritius', 'MU', null),
					(true, 'Mayotte', 'YT', null),
					(true, 'Mexico', 'MX', null),
					(true, 'Micronesia, Federated States of', 'FM', null),
					(true, 'Moldova, Republic of', 'MD', null),
					(true, 'Monaco', 'MC', null),
					(true, 'Mongolia', 'MN', null),
					(true, 'Montenegro', 'ME', null),
					(true, 'Montserrat', 'MS', null),
					(true, 'Morocco', 'MA', null),
					(true, 'Mozambique', 'MZ', null),
					(true, 'Myanmar', 'MM', null),
					(true, 'Namibia', 'NA', null),
					(true, 'Nauru', 'NR', null),
					(true, 'Nepal', 'NP', null),
					(true, 'Netherlands', 'NL', null),
					(true, 'New Caledonia', 'NC', null),
					(true, 'New Zealand', 'NZ', null),
					(true, 'Nicaragua', 'NI', null),
					(true, 'Niger', 'NE', null),
					(true, 'Nigeria', 'NG', null),
					(true, 'Niue', 'NU', null),
					(true, 'Norfolk Island', 'NF', null),
					(true, 'Northern Mariana Islands', 'MP', null),
					(true, 'Norway', 'NO', null),
					(true, 'Oman', 'OM', null),
					(true, 'Pakistan', 'PK', null),
					(true, 'Palau', 'PW', null),
					(true, 'Palestine, State of', 'PS', null),
					(true, 'Panama', 'PA', null),
					(true, 'Papua New Guinea', 'PG', null),
					(true, 'Paraguay', 'PY', null),
					(true, 'Peru', 'PE', null),
					(true, 'Philippines', 'PH', null),
					(true, 'Pitcairn', 'PN', null),
					(true, 'Poland', 'PL', null),
					(true, 'Portugal', 'PT', null),
					(true, 'Puerto Rico', 'PR', null),
					(true, 'Qatar', 'QA', null),
					(true, 'RÃ©union', 'RE', null),
					(true, 'Romania', 'RO', null),
					(true, 'Russian Federation', 'RU', null),
					(true, 'Rwanda', 'RW', null),
					(true, 'Saint BarthÃ©lemy', 'BL', null),
					(true, 'Saint Helena, Ascension and Tristan da Cunha', 'SH', null),
					(true, 'Saint Kitts and Nevis', 'KN', null),
					(true, 'Saint Lucia', 'LC', null),
					(true, 'Saint Martin (French part)', 'MF', null),
					(true, 'Saint Pierre and Miquelon', 'PM', null),
					(true, 'Saint Vincent and the Grenadines', 'VC', null),
					(true, 'Samoa', 'WS', null),
					(true, 'San Marino', 'SM', null),
					(true, 'Sao Tome and Principe', 'ST', null),
					(true, 'Saudi Arabia', 'SA', null),
					(true, 'Senegal', 'SN', null),
					(true, 'Serbia', 'RS', null),
					(true, 'Seychelles', 'SC', null),
					(true, 'Sierra Leone', 'SL', null),
					(true, 'Singapore', 'SG', null),
					(true, 'Sint Maarten (Dutch part)', 'SX', null),
					(true, 'Slovakia', 'SK', null),
					(true, 'Slovenia', 'SI', null),
					(true, 'Solomon Islands', 'SB', null),
					(true, 'Somalia', 'SO', null),
					(true, 'South Africa', 'ZA', null),
					(true, 'South Georgia and the South Sandwich Islands', 'GS', null),
					(true, 'South Sudan', 'SS', null),
					(true, 'Spain', 'ES', null),
					(true, 'Sri Lanka', 'LK', null),
					(true, 'Sudan', 'SD', null),
					(true, 'Suriname', 'SR', null),
					(true, 'Svalbard and Jan Mayen', 'SJ', null),
					(true, 'Swaziland', 'SZ', null),
					(true, 'Sweden', 'SE', null),
					(true, 'Switzerland', 'CH', null),
					(true, 'Syrian Arab Republic', 'SY', null),
					(true, 'Taiwan, Province of China', 'TW', null),
					(true, 'Tajikistan', 'TJ', null),
					(true, 'Tanzania, United Republic of', 'TZ', null),
					(true, 'Thailand', 'TH', null),
					(true, 'Timor-Leste', 'TL', null),
					(true, 'Togo', 'TG', null),
					(true, 'Tokelau', 'TK', null),
					(true, 'Tonga', 'TO', null),
					(true, 'Trinidad and Tobago', 'TT', null),
					(true, 'Tunisia', 'TN', null),
					(true, 'Turkey', 'TR', null),
					(true, 'Turkmenistan', 'TM', null),
					(true, 'Turks and Caicos Islands', 'TC', null),
					(true, 'Tuvalu', 'TV', null),
					(true, 'Uganda', 'UG', null),
					(true, 'Ukraine', 'UA', null),
					(true, 'United Arab Emirates', 'AE', null),
					(true, 'United Kingdom', 'GB', null),
					(true, 'United States', 'US', null),
					(true, 'United States Minor Outlying Islands', 'UM', null),
					(true, 'Uruguay', 'UY', null),
					(true, 'Uzbekistan', 'UZ', null),
					(true, 'Vanuatu', 'VU', null),
					(true, 'Venezuela, Bolivarian Republic of', 'VE', null),
					(true, 'Viet Nam', 'VN', null),
					(true, 'Virgin Islands, British', 'VG', null),
					(true, 'Virgin Islands, U.S.', 'VI', null),
					(true, 'Wallis and Futuna', 'WF', null),
					(true, 'Western Sahara', 'EH', null),
					(true, 'Yemen', 'YE', null),
					(true, 'Zambia', 'ZM', null),
					(true, 'Zimbabwe', 'ZW', null);");

            migrationBuilder.Sql(@"WITH aus_country AS (
					SELECT ""Id"", ""ShortCode"" FROM ""Countries"" WHERE ""Name"" IN ('Australia','United States')
				)

				INSERT INTO public.""States""
					(""IsEnabled"", ""Name"", ""ShortCode"", ""LongCode"", ""CountryId"")
                VALUES (true, 'Australia''s Capital Territory', null, 'ACT', (SELECT Id FROM aus_country),
					(true, 'New South Wales', null, 'NSW', (SELECT Id FROM aus_country),
					(true, 'Northern Territory', null, 'NT', (SELECT Id FROM aus_country),
					(true, 'Queensland', null, 'QLD', (SELECT Id FROM aus_country),
					(true, 'South Australia', null, 'SA', (SELECT Id FROM aus_country),
					(true, 'Tasmania', null, 'TAS', (SELECT Id FROM aus_country),
					(true, 'Victoria', null, 'VIC', (SELECT Id FROM aus_country),
					(true, 'Western Australia', null, 'WA', (SELECT Id FROM aus_country);");

            #endregion "Countries & States"

            migrationBuilder.Sql(@"INSERT INTO public.""Stores""
                (""CreatedAt"", ""CreatedBy"", ""IsDeleteted"", ""IsEnabled"", ""ModifiedAt"", ""ModifiedBy"", ""Code"", ""DefaultPercentageMargin"", ""DefaultProductImageUri"", ""Description"", ""Name"", ""Summary"")
                VALUES(CURRENT_TIMESTAMP, 1, false, true, CURRENT_TIMESTAMP, 1, 'DEMO-STORE', 20, null, null, 'Demo Store', 'The best demo store ever!');
            ");
        }
    }
}